import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:dio/dio.dart';
import 'package:petpogo_app/core/api/api_client.dart';
import 'package:petpogo_app/core/api/peer_api_client.dart';
import 'package:petpogo_app/core/api/request_signature.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:petpogo_app/features/home/data/repository/ai_repository.dart';

void main() {
  signatureTests();
  sessionTests();
  test('AI analyze form data includes required account and optional pet id',
      () {
    final formData = buildAiAnalyzeFormData(
      url: 'https://cdn.example.com/pet.jpg',
      account: '13800138000',
      petId: 'pet-1',
    );
    final fields = Map<String, String>.fromEntries(formData.fields);

    expect(fields['url'], 'https://cdn.example.com/pet.jpg');
    expect(fields['account'], '13800138000');
    expect(fields['pet_id'], 'pet-1');
  });

  test('AI analyze form data rejects an empty account', () {
    expect(
      () => buildAiAnalyzeFormData(
        url: 'https://cdn.example.com/pet.wav',
        account: ' ',
      ),
      throwsArgumentError,
    );
  });
}

class _SignedAdapter implements HttpClientAdapter {
  final requests = <RequestOptions>[];
  final bodies = <List<int>>[];
  int status = 200;
  @override
  Future<ResponseBody> fetch(RequestOptions options, Stream<Uint8List>? body,
      Future<void>? cancelFuture) async {
    requests.add(options);
    bodies.add(body == null ? [] : await body.expand((b) => b).toList());
    return ResponseBody.fromString('{"code":0,"info":{}}', status, headers: {
      'content-type': ['application/json']
    });
  }

  @override
  void close({bool force = false}) {}
}

void signatureTests() {
  test('v2 matches vectors generated by server requestSignature.ts', () {
    final vectors = [
      (
        'POST',
        '/sdkapi/test?b=2&a=1',
        '{"text":"测试"}',
        '09916df7b0125f2c81a6ca3cc026e03bb936b591191e40ced24733618fbd95b6'
      ),
      (
        'GET',
        "/sdkapi/pet/a%2Fb?z=~!*'()&a=2&a=1&q=猫+狗&empty&x=%2B",
        '',
        'a2cf43f22860ce40cd563d6bdba6405f6b5c5cf800bfaad6f7208d536fb5dcf5'
      ),
      (
        'DELETE',
        '/sdkapi/pet/123',
        '',
        'abee7cbbbde59ec4b778861a6b88d5d333aafb7653637aeddd60f4d4b4f8ed3b'
      ),
    ];
    for (final v in vectors) {
      expect(
          sdkSignatureV2(
              secret: 'test-secret',
              method: v.$1,
              uri: Uri.parse('https://example.test${v.$2}'),
              timestamp: '1790127900000',
              nonce: 'nonce_unique_12345',
              body: utf8.encode(v.$3)),
          v.$4);
    }
  });

  test('signatures bind actual JSON, form, multipart, and empty request bytes',
      () async {
    final adapter = _SignedAdapter();
    final client = ApiClient(adapter: adapter);
    await client.post('/sdkapi/ai-proxy/test',
        data: {'text': '猫 🐱', 'account': 'stale'});
    await PeerApiClient(client)
        .post('/pet/info/add', params: {'petName': '猫 狗', 'breed': 'A+B'});
    final form = FormData.fromMap({
      'account': 'stale',
      'text': '中文',
      'file': MultipartFile.fromBytes([0, 1, 255], filename: 'test.bin')
    });
    await client.post('/sdkapi/ai-proxy/test', data: form);
    await client.get('/sdkapi/test?z=2&a=2&a=1');
    await client.delete('/sdkapi/pet/123');
    expect(jsonDecode(utf8.decode(adapter.bodies[0])), {'text': '猫 🐱'});
    expect(Uri.splitQueryString(utf8.decode(adapter.bodies[1])),
        {'petName': '猫 狗', 'breed': 'A+B'});
    final multipart = latin1.decode(adapter.bodies[2]);
    expect(multipart, contains('filename="test.bin"'));
    expect(multipart, isNot(contains('name="account"')));
    final boundary = adapter.requests[2].contentType!.split('boundary=').last;
    expect(multipart, startsWith('--$boundary'));
    expect(multipart, endsWith('--$boundary--\r\n'));
    expect(adapter.bodies[3], isEmpty);
    expect(adapter.bodies[4], isEmpty);
    final nonces = <String>{};
    for (var i = 0; i < adapter.requests.length; i++) {
      final req = adapter.requests[i];
      expect(req.headers['x-signature-version'], '2');
      expect(req.headers['x-key-id'], 'primary');
      final nonce = req.headers['x-nonce'] as String;
      expect(nonce, matches(RegExp(r'^[a-f0-9]{32}$')));
      expect(nonces.add(nonce), isTrue);
      expect(
          req.headers['x-signature'],
          sdkSignatureV2(
            secret: '1q21ee182efd1gf1g@#\$',
            method: req.method,
            uri: req.uri,
            timestamp: req.headers['x-timestamp'] as String,
            nonce: nonce,
            body: adapter.bodies[i],
          ));
    }
  });

  test('v2 failure never retries with v1; non-SDK requests remain unsigned',
      () async {
    final adapter = _SignedAdapter()..status = 403;
    final client = ApiClient(adapter: adapter);
    await expectLater(
        client.post('/sdkapi/test', data: {'x': 1}), throwsA(anything));
    expect(adapter.requests.length, 1);
    expect(adapter.requests.single.headers['x-signature-version'], '2');
    adapter.status = 200;
    await client.get('/public/test');
    expect(adapter.requests.last.headers['x-signature'], isNull);
  });
}

class _SessionAdapter implements HttpClientAdapter {
  final requests = <RequestOptions>[];
  @override
  Future<ResponseBody> fetch(RequestOptions options, Stream<Uint8List>? body,
      Future<void>? cancelFuture) async {
    if (body != null) await body.drain<void>();
    requests.add(options.copyWith(
        headers: Map.of(options.headers), extra: Map.of(options.extra)));
    final ok = options.headers['Authorization'] == 'Bearer renewed';
    return ResponseBody.fromString(
        ok ? '{"ok":true}' : '{"message":"Token 已过期"}', ok ? 200 : 401,
        headers: {
          'content-type': ['application/json']
        });
  }

  @override
  void close({bool force = false}) {}
}

void sessionTests() {
  test('concurrent 401s refresh once and retry with fresh v2 nonces', () async {
    final adapter = _SessionAdapter();
    final client = ApiClient(token: 'old', adapter: adapter);
    final refresh = Completer<String?>();
    var count = 0, logouts = 0;
    client.onRefreshToken = () {
      count++;
      return refresh.future;
    };
    client.onUnauthorized = () => logouts++;
    final work = Future.wait([
      client.get('/sdkapi/a'),
      client.post('/sdkapi/b', data: {'a': 1})
    ]);
    await Future<void>.delayed(const Duration(milliseconds: 40));
    refresh.complete('renewed');
    await work;
    expect(count, 1);
    expect(logouts, 0);
    expect(client.token, 'renewed');
    expect(adapter.requests.length, 4);
    expect(adapter.requests.map((r) => r.headers['x-nonce']).toSet().length, 4);
  });
  test(
      'refresh network failure preserves session; definitive rejection logs out',
      () async {
    final client = ApiClient(token: 'old', adapter: _SessionAdapter());
    var logouts = 0;
    client.onUnauthorized = () => logouts++;
    client.onRefreshToken = () async => throw DioException(
        requestOptions: RequestOptions(path: '/sdkapi/auth/refresh'),
        type: DioExceptionType.connectionError);
    await expectLater(client.get('/sdkapi/a'), throwsA(anything));
    expect(client.token, 'old');
    expect(logouts, 0);
    final req = RequestOptions(path: '/sdkapi/auth/refresh');
    client.onRefreshToken = () async => throw DioException(
        requestOptions: req,
        response: Response(requestOptions: req, statusCode: 401),
        type: DioExceptionType.badResponse);
    await expectLater(client.get('/sdkapi/a'), throwsA(anything));
    expect(logouts, 1);
  });
  test('login failures and anonymous 401s do not terminate a session',
      () async {
    final client = ApiClient(adapter: _SessionAdapter());
    var count = 0;
    client.onUnauthorized = () => count++;
    client.onRefreshToken = () async {
      count++;
      return 'renewed';
    };
    await expectLater(client.get('/sdkapi/public'), throwsA(anything));
    client.setToken('old');
    await expectLater(client.post('/sdkapi/auth/login-pwd'), throwsA(anything));
    expect(count, 0);
  });
  test('logout during refresh cannot replay the old request', () async {
    final adapter = _SessionAdapter();
    final client = ApiClient(token: 'old', adapter: adapter);
    final gate = Completer<String?>();
    client.onRefreshToken = () => gate.future;
    final work = expectLater(client.get('/sdkapi/a'), throwsA(anything));
    await Future<void>.delayed(const Duration(milliseconds: 30));
    client.clearToken();
    gate.complete('renewed');
    await work;
    expect(client.token, isNull);
    expect(adapter.requests.length, 1);
  });
}
